recipes-domd/agl/inc/domd-agl-image.inc
base_set_conf_value produces wrong result if the value to be set
is an empty line, e.g. "". Work this around by providing a
space in the quotes.
=> domd: Work around base_set_conf_value setting empty var

recipes-domd/agl/files/meta-xt-prod-extra/recipes-aos/aos-vis/files/visconfig.json
As currently we can't build go plugins, vis-config use embedded storage and
telemetryemulator adapters. Update VIS config to use embedded adapters.
=> Update visconfig: use embedded plugins

recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-aos/aos-servicemanager/files/first_boot.sh
It is required to use aos/rootCA.crt
=> domf: add update ca certificates into first boot script

recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-core/systemd/systemd_%.bbappend
A file from SRC_URI was removed from files, but still referenced
by the recipe. Fix this by removing the reference.
=> domu: Remove non-existent files from SRC_URI

inc/xen-version.inc
Use "nobranch" in SRC_URI as we are referring to a commit in a tag,
not branch. And bitbake by default assumes branch=master, which makes the
fetcher fail:
ERROR: xen-4.10.0+gitAUTOINC+7b337a7c97-r0 do_fetch: Fetcher failure: Unable to find revision 7b337a7c97c80bc4637d9e8c97002218d5b05e61 in branch master even from upstream
ERROR: xen-4.10.0+gitAUTOINC+7b337a7c97-r0 do_fetch: Fetcher failure for URL: 'git://github.com/xen-troops/xen.git;protocol=https'. Unable to fetch URL from any source.
ERROR: xen-4.10.0+gitAUTOINC+7b337a7c97-r0 do_fetch: Function failed: base_do_fetch
Fix this by providing "nobranch=1": "don't check the SHA validation for branch.
Set this option for the recipe referring to commit which is valid in tag
instead of branch."
Signed-off-by: Oleksandr Andrushchenko …
=> xen: Fix fetcher failure while working with tags

recipes-domd/agl/files/meta-xt-prod-extra/inc/agl-image.inc, recipes-domd/agl/files/meta-xt-prod-extra/recipes-core/logrotate/files/messages, recipes-domd/agl/files/meta-xt-prod-extra/recipes-core/logrotate/files/xen, recipes-domd/agl/files/meta-xt-prod-extra/recipes-core/logrotate/logrotate_%.bbappend, recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-core/images/core-image-minimal.bbappend, recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-core/logrotate/files/messages, recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-core/logrotate/logrotate_%.bbappend
This patch enables logrotate and also adds configs to rotate /var/log/xen
and /var/log/messages logs.
=> domd, domf: enable logrotate

recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-aos/aos-servicemanager/aos-servicemanager_git.bbappend
In order to run nodejs services, we need to have nodejs installed on the
system.
=> domf: add nodejs to aos-servicemanager runtime dependencies

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend, recipes-domd/agl/files/meta-xt-prod-extra/recipes-kernel/linux-libc-headers/linux-libc-headers_%.bbappend, recipes-domd/agl/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend, recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend
Due to current master branch of the Linux kernel repo modified
in order to use BSP-v3.15.0 set fixed revision for prod-aos.
=> Set fixed Linux kernel revision

recipes-domd/agl/files/meta-xt-prod-extra/inc/agl-image.inc, recipes-domd/agl/files/meta-xt-prod-extra/recipes-aos/aos-vis/aos-vis_git.bbappend
Checking AOS_VIS_PLUGINS in core-image-weston.bbappend is not correct. As
this variable is not defined by default in local config. As result
telemetry-emulator is not installed by default regardless telemetry
emulator adapter is installed. The right solution is to add telemetry-
emulator as RDEPENDS in aos-vis recipe.
Reviewed-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>
=> domd: make telemetry-emulator as RDEPENDS of aos-vis

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-h3ulcb.cfg, recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-m3ulcb.cfg
h3ulcb and m3ulcb config files were incorrect merged
during migration to Yocto-thud so fix it.
=> dom0: Fix incorrect merge in conf files

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-xs-m3n.cfg, recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-aos/aos-servicemanager/files/ipforwarding.conf
Pay attention that domd-salvator-xs-m3n.cfg is not tested after
this patch, it's just removal of obvious conflicts.
Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
=> Clean up leftovers after merge conflict

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-extended/displbe/displbe_git.bbappend, recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-extended/libxenbe/libxenbe_git.bbappend, recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-extended/sndbe/sndbe_git.bbappend
The master branches for these components are about to be updated
to support Xen v4.13 release. In order not to break this product,
which is still using Xen v4.12, set fixed revs for the components
in questions.
Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
=> Set fixed revs for libxenbe/snd_be/displ_be

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/eth0.network, recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-extended/guest-addons/guest-addons.bb
Both systemd and guest addons try to install the same eth0.network.
Fix this by using the one provided by systemd.
Fixes: 8f96b8a6ef14 ("domd: Configure ethernet switch ports and VLANs")
=> domd: Use eth0.network from systemd recipe

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-connectivity/sja1105-tool/sja1105-tool/default.xml, recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-core/systemd/files/eth0.1.network, recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-core/systemd/files/eth0.2.network
Proper work of VLANs requires increased size of packets.
This is configured in default.xml
Also properly set DHCPServer on VLAN2
=> Fix settings for router and DHCPServer on VLAN2

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-core/images/core-image-thin-initramfs.bbappend, recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-core/images/core-image-minimal.bbappend
The lack of the entropy prevents openssl to work correctly.
Enable haveged package provided by meta-openembedded layer in order
to ensure that openssl has sufficient entropy during boot time.
Haveged is used to generate random numbers and feed the Linux
random device. Haveged seems to be a good solution in providing
more entropy for hardwareless domains.
Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
=> domu-image-fusion: Enable haveged to provide more entropy

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-extended/guest-addons/guest-addons.bb
2 recipes deploy the same file , what is the cause of the following errors
Collected errors:
check_data_file_clashes: Package systemd wants to install file /home/iusyk/xen/epam/build-workspace/build/tmp/work/x86_64-xt-linux/domd-image-minimal/1.0-r0/repo/build/tmp/work/h3ulcb_cb_xt-poky-linux/core-image-minimal/1.0-r0/rootfs/etc/systemd/network/eth0.network
But that file is already provided by package * guest-addons-bridge-config
ERROR: Unable to install packages. Command '/mnt/work/build/build/tmp/work/x86_64-xt-linux/domd-image-minimal/1.0-r0/repo/build/tmp/work/h3ulcb_cb_xt-poky-linux/core-image-minimal/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /mnt/work/build/build/tmp/work/x86_64-xt-linux/domd-image-minimal/1.0-r0/repo/build/tmp/work/h3ulcb_cb_xt-poky-linux/core-im …
=> domd cetibox: remove eth0.network from guest-addons

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-bsp/alsa-state/files/kingfisher/asound.state
This is patch contains two changes from prod-devel:
https://github.com/xen-troops/meta-xt-prod-devel/pull/204
https://github.com/xen-troops/meta-xt-prod-devel/pull/208/
Summary of changes:
- Remove obsolete part 'rsnddai0ak4613h'
- Rename 'rcar-sound' to 'rcarsound'
- Use dedicated asound.state for SK+KF
=> Align asound.state with prod-devel

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-connectivity/dnsmasq/dnsmasq_2.%.bbappend, recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-core/systemd/files/eth0.2.network
Dnsmasq is used as DHCP server not only for inter-domain network
but for connected devices as well.
Suggested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
=> domd: update setting of dnsmasq

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/provisioning/provisioning.bb
For provisioning purposes we need to have /etc/aos/model_name.txt
file with some info that allows to distinct 'device family'.
This path uses XT_CANONICAL_MACHINE_NAME as model name.
See meta-xt-images/machine/meta-xt-images-rcar-gen3/conf/machine/*
for possible values of machine(model) name.
=> dom0: provisioning: Create model_name.txt

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/provisioning/provisioning.bb
Additional fix for
ca44c06 ("dom0: provisioning: Fix path to model_name.txt")
which in it's turn is fix for
788283d ("dom0: provisioning: Create model_name.txt")
=> dom0: provisioning: Fix2 for model_name.txt

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-connectivity/dnsmasq/dnsmasq_2.%.bbappend
We use special configuration for CB:
- only one device is connected to eth0.2
- this connected device must have IP 10.0.0.100
- connected device can be replaced (we can't hardcode MAC)
For now best solution is to assign 10.0.0.100 to anything
that is connected to eth0.2.
To do this we
1) assign pool of 1 IP
2) prevent dnsmasq from storing leases across reboot
using /var/run as storage this results in reassignment
of addresses on each reboot of CB.
Suggested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
=> domd: dnsmasq: Assign 10.0.0.100 to device on eth0.2

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-core/base-files/base-files_%.bbappend
We see that execution of 'resize' affects some applications during
SSH connection. Also this command is used only for interactive console.
This patch is assembly of two patches from meta-xt-prod-tu2019-demo:
ff27d56 Avoid resizing of console for SSH connections
c39cb17 domd: hide '$' from bitbake
Sign-off's are taken from original patches.
=> domd: Avoid resizing of console for SSH connections

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/cetibox/port-forward-systemd-networkd.conf
On cetibox we have eth0.1 instead of eth0, so appropriate changes
are required for correct inter-domain port forwarding.
Suggested-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
=> domd: network: Fix port forwarding for cetibox

INSTALL.md
PyGitHub is used by build-scripts/build_prod.py
=> INSTALL.md: add pygithub to list of required packages

recipes-dom0/dom0-image-thin-initramfs/dom0-image-thin-initramfs.bbappend, recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/provisioning/provisioning.bb, recipes-domd/domd-image-minimal/domd-image-minimal.bbappend, recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-extended/displaymanager/displaymanager_git.bbappend, recipes-domu/domu-image-fusion/domu-image-fusion.bbappend
Scope
-The manifests dom0.xml, domf.xml, domd.xml are reffered at branch aug-2020-release
-The versions of gitpct.epam.com/epmd-aepr/aos_sdk and github.com/xen-troops/DisplayManager have been fixed
Signed-off-by: Ihor Usyk <ihor_usyk@epam.com>
=> Fix the versions for aug-2020-release

doc/u-boot-env.txt
Fixes: 941bba0 ("u-boot-env.txt: Documented usage of A/B slot approach by u-boot")
Signed-off-by: Yevgen Abramov <Yevgen_Abramov@epam.com>
Reviewed-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
=> u-boot-env.txt: Add missed env to support A/B slot approach by u-boot

doc/u-boot-env.txt
If file is corrupted or empty, we should have default values for missing
vars.
=> [u-boot-env] Set default aos values before loading them from file

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-core/systemd/files/cetibox/eth0.1.network, recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-core/systemd/files/cetibox/eth0.2.network
Beacuse any positive boolean values such as "yes" or "true" are now deprecated.
for IPMasquerade parameter. Value was changed to ipv4.
Signed-off-by: Yevgen Abramov <Yevgen_Abramov@epam.com>
=> [cetibox] Enable IPMasquerade on eth0.1 interface

INSTALL.md
Remove `bizone` as misspeled name of already mentioned package `bison`.
Add `ostree`.
This commit fixes issues:
https://github.com/xen-troops/meta-xt-prod-aos/issues/112 "ostree is not specified in dependencies"
https://github.com/xen-troops/meta-xt-prod-aos/issues/113 "Install.txt: packge bizone does not exist , use bison instead"
=> [INSTALL.md] Fix list of required packages
