xen-troops/meta-xt-prod-aos

recipes-domd/agl/files/meta-xt-prod-extra/recipes-extended/guest-addons/guest-addons.bb

domd: remove reference to already deleted sndbe.service file

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-core/images/core-image-thin-initramfs.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8/defconfig
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-core/images/core-image-minimal.bbappend

To access DomD's network use:
xl network-attach Domain-0 backend=DomD
ifconfig eth0 192.168.0.7

dom0/kernel: Enable network frontend

---

recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-core/images/core-image-minimal.bbappend

domf: Add scp support

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domf.cfg

domf: Increase memory to 1024MiB

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-core/images/core-image-thin-initramfs.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/provisioning/provisioning.bb

dom0: add aos provisioning scripts

---

INSTALL.md
doc/mk_sdcard_image.sh
doc/u-boot-env.txt
doc/uirfs.sh

Add INSTALL.mdL: how to build and how to run.

Add INSTALL.md

---

INSTALL.md

Fix chapters number in INSTALL.md

---

recipes-domd/agl/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7796-m3ulcb-dom0.dts
recipes-domd/agl/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7796-m3ulcb-domd.dts
recipes-domd/agl/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7796-m3ulcb-domu.dts
recipes-domd/agl/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

Signed-off-by: Tomohiro Komagata <tomohiro.komagata.aj@renesas.com>

dom0.dts/domd.dts/domu.dts: Add device tree to support M3ULCB

---

recipes-domd/agl/files/meta-agl/templates/machine/h3ulcb-xt/50_bblayers.conf.inc
recipes-domd/agl/files/meta-agl/templates/machine/m3ulcb-xt/50_bblayers.conf.inc
recipes-domd/agl/files/meta-agl/templates/machine/salvator-x-h3-4x2g-xt/50_bblayers.conf.inc
recipes-domd/agl/files/meta-agl/templates/machine/salvator-x-h3-xt/50_bblayers.conf.inc
recipes-domd/agl/files/meta-agl/templates/machine/salvator-x-m3-xt/50_bblayers.conf.inc

aos: remove unneeded meta-golang layer

---

recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/doc/bblayers.conf.domf-image-minimal

domu: remove unneeded meta-golang layer

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/domf.bb
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domf-salvator-x-h3.cfg

Add domain configuration file for salvator-x-h3 machine

---

recipes-domd/agl/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend

Signed-off-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
Reviewed-by: Andrii Anisov <andrii_anisov@epam.com>

xen: use xt_defconfig as the default configuration

---

recipes-dom0/dom0-image-thin-initramfs/dom0-image-thin-initramfs.bbappend

dom0: Fix typo in manifest file path

---

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-aos/aos-vis/files/visconfig.json

domd: Fix path to aos-vis plugins

---

recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-aos/aos-servicemanager/aos-servicemanager_git.bbappend
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-aos/aos-servicemanager/files/aos_servicemanager.cfg
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-aos/aos-updatemanager/files/aos_updatemanager.cfg

AOS config fixes, found during CES2020 Cetibox integration.

CES2020 Cetibox AOS integration fixes

---

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-core/images/core-image-minimal.bbappend

domd: Add opensshd to core-image-minimal

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-core/images/core-image-thin-initramfs.bbappend
recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-core/images/core-image-minimal.bbappend
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-core/images/core-image-minimal.bbappend

This pull request is compilation of #67, #68, #71 and #70. 
Just minor reformatting and improvements.
"Signed-off" and "Reviewed-by" are taken from original pull requests.

Add provisioning to build

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/provisioning/provisioning.bb

Fixes: 788283d ("dom0: provisioning: Create model_name.txt")

dom0: provisioning: Fix path to model_name.txt

---

INSTALL.txt
recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-core/images/core-image-minimal.bbappend

Wrap cetibox related packages by board specific suffix
Also add cetibox to INSTALL.txt

 Wrap cetibox related packages by board specific suffix

---

conf/layer.conf
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/conf/layer.conf
recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/conf/layer.conf
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/conf/layer.conf
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/conf/layer.conf

These changes are not really necessary but are made to reduce difference with prod-devel:
- Add LAYERSERIES_COMPAT to some layer.conf

Align some files with devel

---

doc/mk_sdcard_image.sh

Take updated version of script from prod-devel.

mk_sdcard_image: sync with prod-devel

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/dom0.bb
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/domd.bb
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/domf.bb
recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-aos/aos-vis/aos-vis_git.bbappend
recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend
recipes-domu/domu-image-fusion/domu-image-fusion.bbappend
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-aos/aos-servicemanager/aos-servicemanager_git.bbappend
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-aos/aos-updatemanager/aos-updatemanager_git.bbappend

The scope of the changes
1.The version of following components are fixed
-aos-vis
-aos-servicemanager
-aos-updatemanager
2.Configuration support
-dom0.bb: DOM0_ALLOWED_PCPUS_h3ulcb-xt = "4-7"
-domf.bb: DOMF_ALLOWED_PCPUS_h3ulcb-xt = "4-7"
-domd.bb: DOMD_CONFIG_h3ulcb-xt = "domd-h3ulcb.cfg"
3.Add device tree for h3ulcb

Support of h3ulcb

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/dom0.bb
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/domd.bb
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/domf.bb
recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

This is cherry-pick of same patches from branch mar-2020-release.

Add h3ulcb to master

---

INSTALL.md

documentation: Describe h3ulcb in list of supported machines

---

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-aos/aos-updatemanager/aos-updatemanager_git.bbappend
recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-aos/aos-updatemanager/files/cetibox/aos_updatemanager.cfg

Signed-off-by: Yevgen Abramov <Yevgen_Abramov@epam.com>

[cetibox] Add ssh update module for UM on domd

---

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-aos/aos-updatemanager/files/cetibox/aos_updatemanager.cfg

[domd] Format UM config for cetibox

---

recipes-domd/domd-image-minimal/files/meta-xt-prod-extra/recipes-aos/aos-vis/files/aos-vis.service

This option is not supported by AoS v5.0.2.

[domd] Remove -j option from VIS service
